apiVersion: batch/v1
kind: Job
metadata:
  name: llm-evaluation
spec:
  template:
    spec:
      containers:
      - name: llm-evaluator
        image: llm-evaluator:latest
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai-api-key
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        volumeMounts:
        - name: results
          mountPath: /app/results
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: evaluation-results-pvc
      restartPolicy: Never
  backoffLimit: 2 
